
@BASE_URL=http://localhost:3001/api

GET {{BASE_URL}}

###

GET {{BASE_URL}}/users

###

GET {{BASE_URL}}/users/12345
###

POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim":"ceydosko önemlii",
    "email":"ceydos1s@gmail.com",
    "userName":"ceydaonemli",
    "password":"1254545"
}

###

PATCH  {{BASE_URL}}/users/6225e728aa3901e3195597b7
Content-Type: application/json

{
    "password":"55656",
    "isim":"ceyceycey"
}

###
DELETE   {{BASE_URL}}/users/62234ae705fe6336be000980
Content-Type: application/json
 