
@BASE_URL=http://localhost:3001/api

GET {{BASE_URL}}

###

GET {{BASE_URL}}/users

###

GET {{BASE_URL}}/users/12345
###

POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim":"Ceyda Önemli",
    "email":"ceydaonemli2@gmail.com",
    "userName":"ceydaonemli",
    "password":"1",
}

###

PATCH  {{BASE_URL}}/users/5454
Content-Type: application/json

{
    "isim":"Ceyda Önemli2",
    "yaş":23,
    "userName":"ceydaonemli2"
}
###
DELETE   {{BASE_URL}}/users/5454
Content-Type: application/json
 